# Versión 1.0
config-version: 1
debug: false
database:
  host: "localhost"
  port: 3306
  database: "minecraft_server"
  username: "minecraft_user"
  password: "password_segura123"
  use-ssl: false
  connection:
    timeout: 5000
    max-pool-size: 10
# Configuración de caché
cache:
  player-stats-expiry: 10
  top-players-refresh: 180
  top-players-max-size: 10
top-players:
  limit: 10
